---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-lint-pipeline-run-
spec:
  pipelineRef:
    name: clone-lint-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
